# ===================================================================
# PERFIL: PROD
# ===================================================================
# %-- prod
spring.config.activate.on-profile=prod
spring.jpa.show-sql=false
