# ===================================================================
# PERFIL: DEV
# ===================================================================
# %-- dev
spring.config.activate.on-profile=dev
spring.jpa.show-sql=true
