# Basic configuration
spring.application.name=${SPRING_APPLICATION_NAME:franchise-api}

# R2DBC Connection
spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/franchise_accenture_db}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME:postgres}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD}
spring.r2dbc.pool.initial-size=${SPRING_R2DBC_POOL_INITIAL_SIZE:5}
spring.r2dbc.pool.max-size=${SPRING_R2DBC_POOL_MAX_SIZE:20}

# Auto-execute schema.sql for R2DBC
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
spring.sql.init.schema-locations=${SPRING_SQL_INIT_SCHEMA_LOCATIONS:classpath:db/schema.sql}


# Server & Base Path
server.port=${SERVER_PORT:9090}
spring.webflux.base-path=${SERVER_SERVLET_CONTEXT_PATH:/accenture}

# Logging configuration
logging.level.root=info
logging.level.com.accenture.franchise=DEBUG
logging.level.org.springframework.r2dbc=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Active profile by default
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
spring.jackson.time-zone=${SPRING_TIMEZONE:America/Bogota}
