# Basic configuration for data access
spring.application.name=${SPRING_APPLICATION_NAME}
spring.r2dbc.url=${SPRING_R2DBC_URL}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD}
spring.r2dbc.pool.initial-size=${SPRING_R2DBC_POOL_INITIAL_SIZE}
spring.r2dbc.pool.max-size=${SPRING_R2DBC_POOL_MAX_SIZE}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.open-in-view=${SPRING_JPA_OPEN_IN_VIEW}
spring.jpa.properties.hibernate.jdbc.time_zone=${SPRING_JPA_TIMEZONE}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_DIALECT}

# Port configuration
server.port=${SERVER_PORT}
spring.webflux.base-path=${SERVER_SERVLET_CONTEXT_PATH}

# Logging configuration
logging.level.root=info
logging.level.com.accenture.franchise=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Active profile by default
spring.profiles.active=${SPRING_PROFILES_ACTIVE}
spring.jackson.time-zone=${SPRING_JPA_TIMEZONE}

